minimumReleaseAge: 4320
minimumReleaseAgeStrict: true
allowBuilds:
  esbuild: true
  msgpackr-extract: false
  msw: true
  onnxruntime-node: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
