minimumReleaseAge: 4320
minimumReleaseAgeStrict: true
allowBuilds:
  esbuild: true
  msgpackr-extract: false
  msw: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  "@biomejs/biome": true
